export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGIN_BEGIN_AIR_LIVE = "LOGIN_BEGIN_AIR_LIVE";
export const LOGIN_SUCCESS_AIR_LIVE = "LOGIN_SUCCESS_AIR_LIVE";
export const LOGIN_FAIL_AIR_LIVE = "LOGIN_FAIL_AIR_LIVE";

export const REGISTER_CUSTOMER_BEGIN = "REGISTER_CUSTOMER_BEGIN";
export const REGISTER_CUSTOMER_SUCCESS = "REGISTER_CUSTOMER_SUCCESS";
export const REGISTER_CUSTOMER_FAIL = "REGISTER_CUSTOMER_FAIL";
export const FORGOT_PASSWORD_BEGIN = "FORGOT_PASSWORD_BEGIN";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const FORGOT_PASSWORD_OTP_BEGIN = "FORGOT_PASSWORD_OTP_BEGIN";
export const FORGOT_PASSWORD_OTP_SUCCESS = "FORGOT_PASSWORD_OTP_SUCCESS";
export const FORGOT_PASSWORD_OTP_FAIL = "FORGOT_PASSWORD_OTP_FAIL";

export const LOGOUT = "LOGOUT";

export const GET_SOURCE_BEGIN = "GET_SOURCE_BEGIN";
export const GET_SOURCE_SUCCESS = "GET_SOURCE_SUCCESS";
export const GET_SOURCE_ERROR = "GET_SOURCE_ERROR";

export const GET_DESTINATION_BEGIN = "GET_DESTINATION_BEGIN";
export const GET_DESTINATION_SUCCESS = "GET_DESTINATION_SUCCESS";
export const GET_DESTINATION_ERROR = "GET_DESTINATION_ERROR";

export const GET_ROUTES_BEGIN = "GET_ROUTES_BEGIN";
export const GET_ROUTES_SUCCESS = "GET_ROUTES_SUCCESS";
export const GET_ROUTES_ERROR = "GET_ROUTES_ERROR";
