export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGIN_BEGIN_AIR_LIVE = "LOGIN_BEGIN_AIR_LIVE";
export const LOGIN_SUCCESS_AIR_LIVE = "LOGIN_SUCCESS_AIR_LIVE";
export const LOGIN_FAIL_AIR_LIVE = "LOGIN_FAIL_AIR_LIVE";

export const REGISTER_CUSTOMER_BEGIN = "REGISTER_CUSTOMER_BEGIN";
export const REGISTER_CUSTOMER_SUCCESS = "REGISTER_CUSTOMER_SUCCESS";
export const REGISTER_CUSTOMER_FAIL = "REGISTER_CUSTOMER_FAIL";
export const FORGOT_PASSWORD_BEGIN = "FORGOT_PASSWORD_BEGIN";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const FORGOT_PASSWORD_OTP_BEGIN = "FORGOT_PASSWORD_OTP_BEGIN";
export const FORGOT_PASSWORD_OTP_SUCCESS = "FORGOT_PASSWORD_OTP_SUCCESS";
export const FORGOT_PASSWORD_OTP_FAIL = "FORGOT_PASSWORD_OTP_FAIL";

export const LOGOUT = "LOGOUT";

export const GET_SOURCE_BEGIN = "GET_SOURCE_BEGIN";
export const GET_SOURCE_SUCCESS = "GET_SOURCE_SUCCESS";
export const GET_SOURCE_ERROR = "GET_SOURCE_ERROR";

export const GET_DESTINATION_BEGIN = "GET_DESTINATION_BEGIN";
export const GET_DESTINATION_SUCCESS = "GET_DESTINATION_SUCCESS";
export const GET_DESTINATION_ERROR = "GET_DESTINATION_ERROR";

export const GET_ROUTES_BEGIN = "GET_ROUTES_BEGIN";
export const GET_ROUTES_SUCCESS = "GET_ROUTES_SUCCESS";
export const GET_ROUTES_ERROR = "GET_ROUTES_ERROR";

// Get Company List
export const GET_COMPANY_LIST_BEGIN = "GET_COMPANY_LIST_BEGIN";
export const GET_COMPANY_LIST_SUCCESS = "GET_COMPANY_LIST_SUCCESS";
export const GET_COMPANY_LIST_ERROR = "GET_COMPANY_LIST_ERROR";

// Get Cancellation Policy
export const GET_CANCELLATION_POLICY_BEGIN = "GET_CANCELLATION_POLICY_BEGIN";
export const GET_CANCELLATION_POLICY_SUCCESS =
  "GET_CANCELLATION_POLICY_SUCCESS";
export const GET_CANCELLATION_POLICY_ERROR = "GET_CANCELLATION_POLICY_ERROR";

// Get Cancellation Policy
export const GET_CURRENT_ACCOUNT_BALANCE_BEGIN =
  "GET_CURRENT_ACCOUNT_BALANCE_BEGIN";
export const GET_CURRENT_ACCOUNT_BALANCE_SUCCESS =
  "GET_CURRENT_ACCOUNT_BALANCE_SUCCESS";
export const GET_CURRENT_ACCOUNT_BALANCE_ERROR =
  "GET_CURRENT_ACCOUNT_BALANCE_ERROR";

// Get Seat Arrangement Details
export const GET_SEAT_ARRANGEMENT_DETAILS_BEGIN =
  "GET_SEAT_ARRANGEMENT_DETAILS_BEGIN";
export const GET_SEAT_ARRANGEMENT_DETAILS_SUCCESS =
  "GET_SEAT_ARRANGEMENT_DETAILS_SUCCESS";
export const GET_SEAT_ARRANGEMENT_DETAILS_ERROR =
  "GET_SEAT_ARRANGEMENT_DETAILS_ERROR";

// Get Amenities
export const GET_AMENITIES_BEGIN = "GET_AMENITIES_BEGIN";
export const GET_AMENITIES_SUCCESS = "GET_AMENITIES_SUCCESS";
export const GET_AMENITIES_ERROR = "GET_AMENITIES_ERROR";

// Get City Pair
export const GET_CITY_PAIR_BEGIN = "GET_CITY_PAIR_BEGIN";
export const GET_CITY_PAIR_SUCCESS = "GET_CITY_PAIR_SUCCESS";
export const GET_CITY_PAIR_ERROR = "GET_CITY_PAIR_ERROR";

// Get Book Seat
export const GET_BOOK_SEAT_BEGIN = "GET_BOOK__SEAT_BEGIN";
export const GET_BOOK_SEAT_SUCCESS = "GET_BOOK_SEAT_SUCCESS";
export const GET_BOOK_SEAT_ERROR = "GET_BOOK_SEAT_ERROR";

// Get Book Seat Print Data
export const GET_FETCH_TICKET_PRINT_DATA_BEGIN =
  "GET_FETCH_TICKET_PRINT_DATA_BEGIN";
export const GET_FETCH_TICKET_PRINT_DATA_SUCCESS =
  "GET_FETCH_TICKET_PRINT_DATA_SUCCESS";
export const GET_FETCH_TICKET_PRINT_DATA_ERROR =
  "GET_FETCH_TICKET_PRINT_DATA_ERROR";

// Get Book Seat
export const GET_BOOK_SEAT_DETAILS_BEGIN = "GET_BOOK_SEAT_DETAILS_BEGIN";
export const GET_BOOK_SEAT_DETAILS_SUCCESS = "GET_BOOK_SEAT_DETAILS_SUCCESS";
export const GET_BOOK_SEAT_DETAILS_ERROR = "GET_BOOK_SEAT_DETAILS_ERROR";

// Get Ticket Status
export const GET_TICKET_STATUS_BEGIN = "GET_TICKET_STATUS_BEGIN";
export const GET_TICKET_STATUS_SUCCESS = "GET_TICKET_STATUS_SUCCESS";
export const GET_TICKET_STATUS_ERROR = "GET_TICKET_STATUS_ERROR";

// Get Ticket Status
export const GET_TICKET_BOOKING_DATA_BEGIN = "GET_TICKET_BOOKING_DATA_BEGIN";
export const GET_TICKET_BOOKING_DATA_SUCCESS =
  "GET_TICKET_BOOKING_DATA_SUCCESS";
export const GET_TICKET_BOOKING_DATA_ERROR = "GET_TICKET_BOOKING_DATA_ERROR";

// ticket cancel ni api badhi
export const CANCELLATION_DETAILS_BEGIN = "CANCELLATION_DETAILS_BEGIN";
export const CANCELLATION_DETAILS_SUCCESS = "CANCELLATION_DETAILS_SUCCESS";
export const CANCELLATION_DETAILS_ERROR = "CANCELLATION_DETAILS_ERROR";

export const CONFIRM_CANCELLATION_BEGIN = "CONFIRM_CANCELLATION_BEGIN";
export const CONFIRM_CANCELLATION_SUCCESS = "CONFIRM_CANCELLATION_SUCCESS";
export const CONFIRM_CANCELLATION_ERROR = "CONFIRM_CANCELLATION_ERROR";

export const CANCELLATION_POLICY_BEGIN = "CANCELLATION_POLICY_BEGIN";
export const CANCELLATION_POLICY_SUCCESS = "CANCELLATION_POLICY_SUCCESS";
export const CANCELLATION_POLICY_ERROR = "CANCELLATION_POLICY_ERROR";

export const JOURNEYDATEWISE_CANCELLATION_POLICY_BEGIN =
  "JOURNEYDATEWISE_CANCELLATION_POLICY_BEGIN";
export const JOURNEYDATEWISE_CANCELLATION_POLICY_SUCCESS =
  "JOURNEYDATEWISE_CANCELLATION_POLICY_SUCCESS";
export const JOURNEYDATEWISE_CANCELLATION_POLICY_ERROR =
  "JOURNEYDATEWISE_CANCELLATION_POLICY_ERROR";

export const ROUTEWISE_CANCELLATION_POLICY_BEGIN =
  "ROUTEWISE_CANCELLATION_POLICY_BEGIN";
export const ROUTEWISE_CANCELLATION_POLICY_SUCCESS =
  "ROUTEWISE_CANCELLATION_POLICY_SUCCESS";
export const ROUTEWISE_CANCELLATION_POLICY_ERROR =
  "ROUTEWISE_CANCELLATION_POLICY_ERROR";

export const PARTIAL_CANCELLATION_DETAILS_BEGIN =
  "PARTIAL_CANCELLATION_DETAILS_BEGIN";
export const PARTIAL_CANCELLATION_DETAILS_SUCCESS =
  "PARTIAL_CANCELLATION_DETAILS_SUCCESS";
export const PARTIAL_CANCELLATION_DETAILS_ERROR =
  "PARTIAL_CANCELLATION_DETAILS_ERROR";

export const CONFIRM_PARTIAL_CANCELLATION_BEGIN =
  "CONFIRM_PARTIAL_CANCELLATION_BEGIN";
export const CONFIRM_PARTIAL_CANCELLATION_SUCCESS =
  "CONFIRM_PARTIAL_CANCELLATION_SUCCESS";
export const CONFIRM_PARTIAL_CANCELLATION_ERROR =
  "CONFIRM_PARTIAL_CANCELLATION_ERROR";

export const FROM_CITY = "FROM_CITY";
export const TO_CITY = "TO_CITY";

export const SELECTED_TAB = "SELECTED_TAB";
